version: "3.9"

services:
  web:
    image: ghcr.io/guymonagan/lms-web:latest
    container_name: lms_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    image: ghcr.io/guymonagan/lms-web:latest
    container_name: lms_celery
    command: celery -A config worker -l info
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery-beat:
    image: ghcr.io/guymonagan/lms-web:latest
    container_name: lms_celery_beat
    command: celery -A config beat -l info
    env_file:
      - .env
    depends_on:
      - web
      - redis

  db:
    image: postgres:15
    container_name: lms_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    container_name: lms_redis

volumes:
  postgres_data:
